name: amplicon-general
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1.3
  - r-tidyverse=1.3.2
  - r-vegan=2.6_4
  - r-dendextend=1.16.0
  - bioconductor-dada2=1.22.0
  - bioconductor-decipher=2.22.0
  - bioconductor-phyloseq=1.38.0
  - bioconductor-deseq2=1.34.0
